
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wmcmihtejmzhtcwurxvv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndtY21paHRlam16aHRjd3VyeHZ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5NzM1MjMsImV4cCI6MjA2MDU0OTUyM30.8KmBeJBuleFbNKrjtSyw96Wk83X3YByeCLzm2B71JVs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storage: localStorage
  }
});
